version: '2'
services:
    gitlab:
      image: 'lai1208/gitlab-ce-zh:11.2.3'
      restart: unless-stopped
      hostname: 'git.gdepb.gov.cn'
      name: gitlab
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://git.gdepb.gov.cn'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
          # 比如下面的电子邮件的配置：
          # gitlab_rails['smtp_enable'] = true
          # gitlab_rails['smtp_address'] = "smtp.163.com"
          # gitlab_rails['smtp_port'] = 25
          # gitlab_rails['smtp_user_name'] = "098303786@163.com"
          # gitlab_rails['smtp_password'] = "lai_devtest"
          # gitlab_rails['smtp_authentication'] = "login"
          # gitlab_rails['smtp_enable_starttls_auto'] = true
          # gitlab_rails['smtp_tls'] = true
          # gitlab_rails['gitlab_email_from'] = '098303786@163.com'
      ports:
        - '80:80'
        - '443:443'
        - '10022:22'
      volumes:
        - config:/etc/gitlab
        - data:/var/opt/gitlab
        - logs:/var/log/gitlab
volumes:
    config:/srv/gitlab/config
    data:/srv/gitlab/data
    logs:/srv/gitlab/logs